services:
  frontend:
    image: dvunc-frontend:latest
    ports:
      - "3000:80"
    environment:
      - REACT_APP_BACKEND_SCHEMA=http
      - REACT_APP_BACKEND_HOST=backend
      - REACT_APP_BACKEND_PORT=8000
    depends_on:
      - backend

  backend:
    image: dvunc-backend:latest
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_HOST=db
      - DB_PORT=5432
      - SECRET_KEY=${SECRET_KEY}
      - DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./db/pg_dump.sql:/docker-entrypoint-initdb.d/pg_dump.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
